const audioMainContainer = document.querySelector('.sound-options')


const audioTitle = [
    'R Aquarii Sonification <br/> --', 
    'Audio from NASA’s Juno Mission: Europa Flyby', 
    "Black Hole 'Sound' in the Perseus Galaxy Cluster",
    'Voyager: Interstellar Plasma Sounds',
    'First Audio Recording of Sounds on Mars',
    `Stephan's Quintet Sonification`
]
    /* --------------------------*/
const audioFile  = [
    'R Aquarii Sonification.wav', 
    'Europa Flyby.wav',
    'Perseus Galaxy Cluster.mp3',
    'Voyager Interstellar Plasma Sounds.mp3',
    'First Audio Recording of Sounds on Mars.wav',
    `Stephan Quintet Sonification.wav` 
]
    /* --------------------------*/
const audioBgImg = [
    'R Aquarii.png', 
    'Europa Flyby.jpg',
    'Perseus Galaxy Cluster.jpg',
    'Voyager Interstellar Plasma Sounds.jpg',
    'First Audio Recording of Sounds on Mars.jpg',
    'Stephan Quintet Sonification.jpg'
]
    /* --------------------------*/
const audioDescription = [
    `The system called R Aquarii contains two stars — a white dwarf and a red giant — in orbit around each other. In a composite visual image, Hubble data (red and blue) reveal spectacular structures that are evidence of outbursts generated by the pair of stars buried at the center of the image. X-rays from Chandra show a jet from the white dwarf banging into the material surrounding it and creating shock waves. In the sonification of R Aquarii, the piece evolves as a radar-like scan of the image, clockwise starting at the 12 o’clock position. The volume changes in proportion to the brightness of sources in Hubble’s visible light and Chandra’s X-ray image, while the distance from the center dictates the musical pitch (higher notes are farther out). The deep thuds toward the four corners are “diffraction spikes,” which are artifacts from the bright central star. Listeners can hear jets from the white dwarf as the cursor travels near the two o’clock and eight o’clock positions. The ribbon-like arcs captured by Hubble create a rising and falling melody that sounds similar to a set of singing bowls (metal bowls that produce different sounds and tones when struck with a mallet), while the Chandra data are rendered to sound more like a synthetic and windy purr.
    NASA/CXC/SAO/K.Arcand, SYSTEM Sounds (M. Russo, A. Santaguida)`,

    `Measurements collected by the Waves instrument aboard NASA’s Juno spacecraft during its close flyby of Jupiter’s moon Europa on Sept. 29, 2022 have been converted to an audible frequency. The variation of frequency of the plasma waves observed near Europa can be heard as the plasma density varies.
    For more information about NASA’s Juno mission, visit: nasa.gov/juno and missionjuno.com
    Details about the Europa flyby can be found at: www.nasa.gov/feature/jpl/nasa-s…-s-icy-moon-europa
    Credit: NASA/JPL-Caltech/SwRI/Univ of Iowa`,

    `Astronomical data from the supermassive black hole at the center of the Perseus galaxy cluster has been translated into sounds we can hear.
    artist: Chandra X-ray Observatory
    (Credit: NASA/CXC/SAO/K. Arcand, M. Russo & A. Santaguida)`,

    
    `Voyager 1's plasma wave instrument detected the vibrations of dense interstellar plasma, or ionized gas, from October to November 2012 and April to May 2013. This sound reproduces the amplitude and frequency of the plasma waves as "heard" by Voyager 1.`,

    `This recording was made by the SuperCam instrument on NASA’s Perseverance Mars rover on Feb. 19, 2021, just about 18 hours after landing on the mission’s first sol or Martian day. The rover’s mast, holding the microphone, was still stowed on Perseverance’s deck, and so the sound is muffled, a little like the sound one hears listening to a seashell or having a hand cupped over the ear. Just a little wind can be heard.
    Credit: NASA/JPL-Caltech/LANL/CNES/CNRS/ISAE-Supaero`,

    `In Stephan’s Quintet, four galaxies move around each other, held together by gravity, while a fifth galaxy sits in the frame but is actually at a much different distance. A visual image of Stephan’s Quintet contains infrared light from the James Webb Space Telescope (red, orange, yellow, green, and blue) with additional data from the Spitzer Space Telescope (red, green, and blue) and X-ray light from Chandra (light blue). A sonification of these data begins at the top and scans the image downward. As the cursor moves, the pitch changes in relationship to the brightness in different ways. The background galaxies and foreground stars in the visual images Webb detects are mapped to different notes on a synthetic glass marimba. Meanwhile, stars with diffraction spikes are played as crash cymbals. The galaxies of Stephan’s Quintet themselves are heard as smoothly changing frequencies as the scan passes over them. The X-rays from Chandra, which reveal a shock wave that has superheated gas to tens of millions of degrees, are represented by a synthetic string sound`
]
/* --------------------------*/

let sample = ``

for(let i = 0; i < audioTitle.length; i++){
    sample += `
    <div class="small-div">
        <div class="bg-div-inner">
            <div class="curten-inner"></div>
            <img src="images/listenTheCosmosImgs/${audioBgImg[i]}" alt="R Aquarii Image" />
        </div>
        <div class="text-audio-content">
            <h3>${audioTitle[i]}</h3>
            <audio controls>
                <source src="soundFiles/${audioFile[i]}" type="audio/wav">
                Your browser does not support the audio element.
            </audio>
            <button class="audio-desc-btn-${i}">View description</button>
        </div>
    </div>
    `
}
audioMainContainer.innerHTML = `${sample}`

const openingClosingDescriptionFunc = function(state, blurDegree){
    audioTextDescriptionContainer.style.display = state
    document.querySelector('.title').style.filter = `blur(${blurDegree}px)`
    document.querySelector('.main-description').style.filter = `blur(${blurDegree}px)`
    // audioMainContainer.style.filter = `blur(${blurDegree}px)`
    let inverseState = ''
    if(state == 'block'){inverseState = 'none'}
    else{inverseState = 'block'} 
    audioMainContainer.style.display = `${inverseState}`
    
}


const audioTextDescriptionContainer = document.querySelector('.audio-text-description')


// 
for(let z = 0; z < audioDescription.length ; z++){
    document.querySelector(`.audio-desc-btn-${z}`).addEventListener('click', ()=>{
        audioTextDescriptionContainer.innerHTML =   `
        
        <div class="text-desc-bg">
            <div class="curten-inner-2"></div>
            <img src="images/listenTheCosmosImgs/${audioBgImg[z]}" class="audio-text-desc-img" alt=""/>
        </div>
        <img src="images/icons/x-mark.png" class="text-desc-xmark" alt=""/>
        <div class="audio-text-discription-wrapper">
            <h3>${audioTitle[z]}</h3>
            <hr />
            <p>${audioDescription[z]}</p>
        </div>
        `
        document.querySelector('.text-desc-xmark').addEventListener('click', ()=>{
           openingClosingDescriptionFunc('none', 0)
        })
// 
        openingClosingDescriptionFunc('block', 40) 
        // this blurs this
    })
}
